spring:
  ai:
    anthropic:
      api-key: {ANTHROPIC_KEY}
      chat:
        options:
          model: claude-3-7-sonnet-20250219
    mcp:
      client:
        enabled: true
        toolcallback:
          enabled: true
        sse:
          connections:
            author-tool-server:
              url: http://localhost:8088
              enabled: true
        stdio:
          connections:
            brave-search:
              command: npx.cmd
              args:
                - "-y"
                - "@modelcontextprotocol/server-brave-search"
              env:
                BRAVE_API_KEY: {BRAVE_API_KEY}

            filesystem:
              command: npx.cmd
              args:
                - "-y"
                - "@modelcontextprotocol/server-filesystem"
                - "./"
        type: SYNC
        request-timeout: 60s

logging:
  level:
    org:
      springframework:
        ai: DEBUG